"""Add note models

Revision ID: 1831d2b3e931
Revises: 
Create Date: 2026-10-01 00:14:41.867210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1831d2b3e931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_notes_id'), 'experiment_notes', ['id'], unique=False)
    op.create_table('note_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('markdown', 'latex', 'table', 'chemical_structure', name='blocktype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['experiment_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_blocks_id'), 'note_blocks', ['id'], unique=False)
    op.create_table('note_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('current_hash', sa.String(), nullable=False),
    sa.Column('diff_patch', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['experiment_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_revisions_id'), 'note_revisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_revisions_id'), table_name='note_revisions')
    op.drop_table('note_revisions')
    op.drop_index(op.f('ix_note_blocks_id'), table_name='note_blocks')
    op.drop_table('note_blocks')
    op.drop_index(op.f('ix_experiment_notes_id'), table_name='experiment_notes')
    op.drop_table('experiment_notes')
    # ### end Alembic commands ###
