"""Add is_deleted to ExperimentNote

Revision ID: 1fa45d1f583b
Revises: 1831d2b3e931
Create Date: 2026-10-01 00:47:59.283968

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fa45d1f583b"
down_revision: str | Sequence[str] | None = "1831d2b3e931"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiment_notes",
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiment_notes", "is_deleted")
    # ### end Alembic commands ###
