# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import labflow_pb2 as labflow__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in labflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostServiceStub:
    """─── Services ────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinSession = channel.unary_unary(
                '/labflow.v1.HostService/JoinSession',
                request_serializer=labflow__pb2.JoinRequest.SerializeToString,
                response_deserializer=labflow__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/labflow.v1.HostService/SubmitTask',
                request_serializer=labflow__pb2.TaskRequest.SerializeToString,
                response_deserializer=labflow__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.SandboxWrite = channel.unary_unary(
                '/labflow.v1.HostService/SandboxWrite',
                request_serializer=labflow__pb2.SandboxWriteRequest.SerializeToString,
                response_deserializer=labflow__pb2.SandboxReadResponse.FromString,
                _registered_method=True)
        self.SandboxRead = channel.unary_unary(
                '/labflow.v1.HostService/SandboxRead',
                request_serializer=labflow__pb2.SandboxReadRequest.SerializeToString,
                response_deserializer=labflow__pb2.SandboxReadResponse.FromString,
                _registered_method=True)


class HostServiceServicer:
    """─── Services ────────────────────────────────────────────────────────────────

    """

    def JoinSession(self, request, context):
        """Key validation & session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Dispatch a task to the agent runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SandboxWrite(self, request, context):
        """Binary sandbox I/O (delegated to core-engine via FFI)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SandboxRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinSession': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinSession,
                    request_deserializer=labflow__pb2.JoinRequest.FromString,
                    response_serializer=labflow__pb2.JoinResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=labflow__pb2.TaskRequest.FromString,
                    response_serializer=labflow__pb2.TaskResponse.SerializeToString,
            ),
            'SandboxWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.SandboxWrite,
                    request_deserializer=labflow__pb2.SandboxWriteRequest.FromString,
                    response_serializer=labflow__pb2.SandboxReadResponse.SerializeToString,
            ),
            'SandboxRead': grpc.unary_unary_rpc_method_handler(
                    servicer.SandboxRead,
                    request_deserializer=labflow__pb2.SandboxReadRequest.FromString,
                    response_serializer=labflow__pb2.SandboxReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'labflow.v1.HostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('labflow.v1.HostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostService:
    """─── Services ────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def JoinSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/labflow.v1.HostService/JoinSession',
            labflow__pb2.JoinRequest.SerializeToString,
            labflow__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/labflow.v1.HostService/SubmitTask',
            labflow__pb2.TaskRequest.SerializeToString,
            labflow__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SandboxWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/labflow.v1.HostService/SandboxWrite',
            labflow__pb2.SandboxWriteRequest.SerializeToString,
            labflow__pb2.SandboxReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SandboxRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/labflow.v1.HostService/SandboxRead',
            labflow__pb2.SandboxReadRequest.SerializeToString,
            labflow__pb2.SandboxReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_stream(
                '/labflow.v1.AgentService/ExecuteTask',
                request_serializer=labflow__pb2.TaskRequest.SerializeToString,
                response_deserializer=labflow__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ExecuteCode = channel.unary_unary(
                '/labflow.v1.AgentService/ExecuteCode',
                request_serializer=labflow__pb2.ExecuteCodeRequest.SerializeToString,
                response_deserializer=labflow__pb2.ExecuteCodeResponse.FromString,
                _registered_method=True)
        self.AgentEventStream = channel.stream_stream(
                '/labflow.v1.AgentService/AgentEventStream',
                request_serializer=labflow__pb2.AgentEventRequest.SerializeToString,
                response_deserializer=labflow__pb2.AgentEventResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Host → Agent: push a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCode(self, request, context):
        """Host → Agent: push code for isolated execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentEventStream(self, request_iterator, context):
        """Bidirectional stream for UI events and analysis results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=labflow__pb2.TaskRequest.FromString,
                    response_serializer=labflow__pb2.TaskResponse.SerializeToString,
            ),
            'ExecuteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCode,
                    request_deserializer=labflow__pb2.ExecuteCodeRequest.FromString,
                    response_serializer=labflow__pb2.ExecuteCodeResponse.SerializeToString,
            ),
            'AgentEventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentEventStream,
                    request_deserializer=labflow__pb2.AgentEventRequest.FromString,
                    response_serializer=labflow__pb2.AgentEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'labflow.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('labflow.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/labflow.v1.AgentService/ExecuteTask',
            labflow__pb2.TaskRequest.SerializeToString,
            labflow__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/labflow.v1.AgentService/ExecuteCode',
            labflow__pb2.ExecuteCodeRequest.SerializeToString,
            labflow__pb2.ExecuteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentEventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/labflow.v1.AgentService/AgentEventStream',
            labflow__pb2.AgentEventRequest.SerializeToString,
            labflow__pb2.AgentEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
