"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _TaskStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TaskStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TaskStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TASK_STATUS_UNSPECIFIED: _TaskStatus.ValueType  # 0
    TASK_STATUS_PENDING: _TaskStatus.ValueType  # 1
    TASK_STATUS_RUNNING: _TaskStatus.ValueType  # 2
    TASK_STATUS_DONE: _TaskStatus.ValueType  # 3
    TASK_STATUS_FAILED: _TaskStatus.ValueType  # 4

class TaskStatus(_TaskStatus, metaclass=_TaskStatusEnumTypeWrapper): ...

TASK_STATUS_UNSPECIFIED: TaskStatus.ValueType  # 0
TASK_STATUS_PENDING: TaskStatus.ValueType  # 1
TASK_STATUS_RUNNING: TaskStatus.ValueType  # 2
TASK_STATUS_DONE: TaskStatus.ValueType  # 3
TASK_STATUS_FAILED: TaskStatus.ValueType  # 4
Global___TaskStatus: _TypeAlias = TaskStatus  # noqa: Y015

@_typing.final
class Session(_message.Message):
    """─── Session / Collaboration ──────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    OWNER_KEY_FIELD_NUMBER: _builtins.int
    PEER_IDS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    owner_key: _builtins.str
    """SHA-256 hex of the API key"""
    created_at: _builtins.int
    """Unix timestamp (seconds)"""
    @_builtins.property
    def peer_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        owner_key: _builtins.str = ...,
        peer_ids: _abc.Iterable[_builtins.str] | None = ...,
        created_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "owner_key", b"owner_key", "peer_ids", b"peer_ids", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Session: _TypeAlias = Session  # noqa: Y015

@_typing.final
class JoinRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    API_KEY_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    api_key: _builtins.str
    """raw key — validated server-side"""
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        api_key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JoinRequest: _TypeAlias = JoinRequest  # noqa: Y015

@_typing.final
class JoinResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    token: _builtins.str
    """short-lived JWT for this session"""
    message: _builtins.str
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
        token: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted", "message", b"message", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JoinResponse: _TypeAlias = JoinResponse  # noqa: Y015

@_typing.final
class TaskRequest(_message.Message):
    """─── Agent Tasks ─────────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    session_id: _builtins.str
    payload: _builtins.str
    """JSON-encoded task parameters"""
    priority: _builtins.int
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        payload: _builtins.str = ...,
        priority: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "priority", b"priority", "session_id", b"session_id", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskRequest: _TypeAlias = TaskRequest  # noqa: Y015

@_typing.final
class TaskResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    result: _builtins.str
    """JSON-encoded result"""
    status: Global___TaskStatus.ValueType
    error: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        result: _builtins.str = ...,
        status: Global___TaskStatus.ValueType = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "result", b"result", "status", b"status", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskResponse: _TypeAlias = TaskResponse  # noqa: Y015

@_typing.final
class ExecuteCodeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    MAX_MEMORY_FIELD_NUMBER: _builtins.int
    MAX_CPU_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    code: _builtins.str
    """Python or Wasm code string"""
    language: _builtins.str
    """e.g., "python", "wasm" """
    max_memory: _builtins.int
    """Max memory limit in bytes"""
    max_cpu: _builtins.int
    """CPU / Fuel limit"""
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        code: _builtins.str = ...,
        language: _builtins.str = ...,
        max_memory: _builtins.int = ...,
        max_cpu: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "language", b"language", "max_cpu", b"max_cpu", "max_memory", b"max_memory", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecuteCodeRequest: _TypeAlias = ExecuteCodeRequest  # noqa: Y015

@_typing.final
class ExecuteCodeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    MEMORY_USED_BYTES_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    output: _builtins.str
    """stdout or execution result"""
    error: _builtins.str
    """stderr or error message"""
    memory_used_bytes: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        output: _builtins.str = ...,
        error: _builtins.str = ...,
        memory_used_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "memory_used_bytes", b"memory_used_bytes", "output", b"output", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecuteCodeResponse: _TypeAlias = ExecuteCodeResponse  # noqa: Y015

@_typing.final
class SandboxWriteRequest(_message.Message):
    """─── Sandbox I/O bridge ──────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    offset: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        offset: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "offset", b"offset", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SandboxWriteRequest: _TypeAlias = SandboxWriteRequest  # noqa: Y015

@_typing.final
class SandboxReadRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    offset: _builtins.int
    size: _builtins.int
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        offset: _builtins.int = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["offset", b"offset", "session_id", b"session_id", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SandboxReadRequest: _TypeAlias = SandboxReadRequest  # noqa: Y015

@_typing.final
class SandboxReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    ok: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        ok: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "error", b"error", "ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SandboxReadResponse: _TypeAlias = SandboxReadResponse  # noqa: Y015

@_typing.final
class ChartState(_message.Message):
    """─── CRDT Trackable Structures ───────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    CHART_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    chart_id: _builtins.str
    type: _builtins.str
    data: _builtins.bytes
    """Binary payload of chart data"""
    def __init__(
        self,
        *,
        chart_id: _builtins.str = ...,
        type: _builtins.str = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chart_id", b"chart_id", "data", b"data", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChartState: _TypeAlias = ChartState  # noqa: Y015

@_typing.final
class ChemicalStructure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STRUCTURE_ID_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    structure_id: _builtins.str
    format: _builtins.str
    """e.g., "SMILES", "MOL" """
    payload: _builtins.str
    def __init__(
        self,
        *,
        structure_id: _builtins.str = ...,
        format: _builtins.str = ...,
        payload: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["format", b"format", "payload", b"payload", "structure_id", b"structure_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChemicalStructure: _TypeAlias = ChemicalStructure  # noqa: Y015

@_typing.final
class MarkdownAST(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOCUMENT_ID_FIELD_NUMBER: _builtins.int
    ROOT_NODE_FIELD_NUMBER: _builtins.int
    document_id: _builtins.str
    root_node: _builtins.str
    """JSON representation of the AST"""
    def __init__(
        self,
        *,
        document_id: _builtins.str = ...,
        root_node: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["document_id", b"document_id", "root_node", b"root_node"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MarkdownAST: _TypeAlias = MarkdownAST  # noqa: Y015

@_typing.final
class DeltaMutation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGET_ID_FIELD_NUMBER: _builtins.int
    DELTA_DATA_FIELD_NUMBER: _builtins.int
    target_id: _builtins.str
    delta_data: _builtins.bytes
    """Optimized difference data for vectors/matrices"""
    def __init__(
        self,
        *,
        target_id: _builtins.str = ...,
        delta_data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delta_data", b"delta_data", "target_id", b"target_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeltaMutation: _TypeAlias = DeltaMutation  # noqa: Y015

@_typing.final
class AgentEventRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    event_type: _builtins.str
    """e.g., "CANVAS_CLICK", "PARAMETER_CHANGE" """
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        event_type: _builtins.str = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_type", b"event_type", "payload", b"payload", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AgentEventRequest: _TypeAlias = AgentEventRequest  # noqa: Y015

@_typing.final
class AgentEventResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    RESPONSE_TYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    response_type: _builtins.str
    """e.g., "ANALYSIS_RESULT", "CODE_GENERATION" """
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        response_type: _builtins.str = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "response_type", b"response_type", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AgentEventResponse: _TypeAlias = AgentEventResponse  # noqa: Y015
