// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// SHA-256 hex of the API key
    #[prost(string, tag = "2")]
    pub owner_key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub peer_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Unix timestamp (seconds)
    #[prost(int64, tag = "4")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// raw key — validated server-side
    #[prost(string, tag = "2")]
    pub api_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinResponse {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    /// short-lived JWT for this session
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// JSON-encoded task parameters
    #[prost(string, tag = "3")]
    pub payload: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub priority: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskResponse {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// JSON-encoded result
    #[prost(string, tag = "2")]
    pub result: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCodeRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// Python or Wasm code string
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    /// e.g., "python", "wasm"
    #[prost(string, tag = "3")]
    pub language: ::prost::alloc::string::String,
    /// Max memory limit in bytes
    #[prost(uint64, tag = "4")]
    pub max_memory: u64,
    /// CPU / Fuel limit
    #[prost(uint64, tag = "5")]
    pub max_cpu: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCodeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// stdout or execution result
    #[prost(string, tag = "2")]
    pub output: ::prost::alloc::string::String,
    /// stderr or error message
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub memory_used_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxWriteRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxReadRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint32, tag = "3")]
    pub size: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxReadResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChartState {
    #[prost(string, tag = "1")]
    pub chart_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    /// Binary payload of chart data
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChemicalStructure {
    #[prost(string, tag = "1")]
    pub structure_id: ::prost::alloc::string::String,
    /// e.g., "SMILES", "MOL"
    #[prost(string, tag = "2")]
    pub format: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payload: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkdownAst {
    #[prost(string, tag = "1")]
    pub document_id: ::prost::alloc::string::String,
    /// JSON representation of the AST
    #[prost(string, tag = "2")]
    pub root_node: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeltaMutation {
    #[prost(string, tag = "1")]
    pub target_id: ::prost::alloc::string::String,
    /// Optimized difference data for vectors/matrices
    #[prost(bytes = "vec", tag = "2")]
    pub delta_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEventRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// e.g., "CANVAS_CLICK", "PARAMETER_CHANGE"
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEventResponse {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// e.g., "ANALYSIS_RESULT", "CODE_GENERATION"
    #[prost(string, tag = "2")]
    pub response_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// CRDT Operations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrdtOperation {
    #[prost(enumeration = "crdt_operation::OpType", tag = "1")]
    pub op_type: i32,
    /// Unique id of the character/element
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    /// To establish tree structure or sequence
    #[prost(string, tag = "3")]
    pub parent_id: ::prost::alloc::string::String,
    /// For arrays/strings
    #[prost(uint32, tag = "4")]
    pub index: u32,
    /// Content to insert/update
    #[prost(string, tag = "5")]
    pub value: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CrdtOperation`.
pub mod crdt_operation {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum OpType {
        Insert = 0,
        Delete = 1,
        Update = 2,
    }
    impl OpType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Insert => "INSERT",
                Self::Delete => "DELETE",
                Self::Update => "UPDATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INSERT" => Some(Self::Insert),
                "DELETE" => Some(Self::Delete),
                "UPDATE" => Some(Self::Update),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrdtDeltaChunk {
    #[prost(string, tag = "1")]
    pub document_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub operations: ::prost::alloc::vec::Vec<CrdtOperation>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Done = 3,
    Failed = 4,
}
impl TaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TASK_STATUS_UNSPECIFIED",
            Self::Pending => "TASK_STATUS_PENDING",
            Self::Running => "TASK_STATUS_RUNNING",
            Self::Done => "TASK_STATUS_DONE",
            Self::Failed => "TASK_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TASK_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "TASK_STATUS_PENDING" => Some(Self::Pending),
            "TASK_STATUS_RUNNING" => Some(Self::Running),
            "TASK_STATUS_DONE" => Some(Self::Done),
            "TASK_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
